Created Project
AyoMoses1/Crypto-Metrics pull request #3
Opened 2023-03-24 19:53 UTC by AyoMoses1

I was able to develop every part of this project following the requirements as stated in this [repo](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md)
Please feel free to review and drop your feedbacks where necessary

2023-03-24 21:29 UTC, OLIPLICHE requested changes
Hi @AyoMoses1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The App is working fine 👍 
- The App is well deployed 👍 
- Video presentation 👍 

## Required Changes ♻️
_Check the comments under the review._
NB: All the changes I have requested are based on the project requirements. Believe me, your App design will make your App more attractive
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 21:29 UTC, OLIPLICHE commented on README.md
> +## 🙏 Acknowledgments <a name="acknowledgements"></a>
- Hi, I would advise you to  "Acknowledge" or give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). I am requesting this because it is part of your project requirements

2023-03-24 21:29 UTC, OLIPLICHE commented on src/App.css
> +  margin-top: 2rem;
- [ ] Hi, You have done a great job. Now I would advise you to follow the design requested by the project:
- Can you follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including:
   * Typography: font face, size, and weight
   * Layout: composition and space between elements.
You can select one main color for the app and be consistent
- Can you provide the "Back" button (<), When the user clicks on the user navigates to the home page?

- [ ] See your Application:

- Home page
![Capture1](https://user-images.githubusercontent.com/63972670/227641024-eb712ce9-d5d1-4334-8e17-88fa3edb88d4.PNG)

- Detail page

![1](https://user-images.githubusercontent.com/63972670/227641242-b9d031fe-4b1d-44fd-87d5-aa977e053b46.PNG)

- [ ] Original Design:

![Capture](https://user-images.githubusercontent.com/63972670/227641607-47a18aa2-7fe0-47ce-a4a3-83dbed612a2d.PNG)

2023-03-24 21:29 UTC, OLIPLICHE commented on src/__tests__/App.test.js
> +});
- [ ] Hi, I would advise you to work on the test again. the test did not pass.

![1](https://user-images.githubusercontent.com/63972670/227644196-7bd9c836-dc5b-4a78-992e-06a86617be2f.PNG)

2023-03-25 11:35 UTC, AshakaE requested changes
Hi @AyoMoses1 🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Well done working on the test cases 👏 
- Good job implementing the previous requested changes 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 11:35 UTC, AshakaE commented on src/__tests__/Routes/Details.test.js
> +});
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/67957533/227715045-c71f6b1f-4dec-4082-b43d-7eee5ee6e36c.png">

- [ ] Kindly fix this test case

2023-03-25 12:01 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @AyoMoses1  :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: All tests are passing
:heavy_check_mark: Follow gitflow.


## Optional suggestions 🤷‍♂️

- ***[OPTIONAL]*** Consider using the capital letter as the first letter of a commit message, as it is professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 12:01 UTC, merged